name: Build Pull Request
on: pull_request
jobs:
  test_job:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
      - name: Assemble Debug
        run: ./gradlew assembleDebug
